### Get all persons ###
GET http://localhost:3001/api/persons

### Get specific person ###
GET http://localhost:3001/api/persons/6843886bbcdcf2fe0b637cee

### Add new person ###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Joe Momma",
  "number": "119"
}

### Delete Person ###
DELETE http://localhost:3001/api/persons/6847865ee0e9a095e3eeddce

### Change number ###
POST http://localhost:3001/api/persons/6843886bbcdcf2fe0b637cee
Content-Type: application/json

{
  "name": "Jane Doe",
  "number": "12345",
  "id": "6843886bbcdcf2fe0b637cee"
}