### GET REQUEST ###
GET http://localhost:3003/api/blogs

### GOOD POST REQUEST ###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIzIiwiaWQiOiI2ODYyMjg4MTk2MjBlZGFjYjhhNzM3ZTAiLCJpYXQiOjE3NTI0NTYzNjMsImV4cCI6MTc1MjQ1OTk2M30.8DRjHt2QuVWtSO8qd_XcKgkAzeMOpZ1I1REmG-xc17M

{
	"title": "Book About Bacon 5",
	"author": "Wolfram Alpha",
	"url": "www.baconbacon.com"
}

### BAD POST REQUEST ###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "Some Book",
	"author": "John Doe"
}

### DELETE REQUEST ###
DELETE http://localhost:3003/api/blogs/68673f363370993b79bd9558
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI0IiwiaWQiOiI2ODYyY2U2OTlkNGMzZTIxZTIxYzIzNDQiLCJpYXQiOjE3NTEzMTAxMjYsImV4cCI6MTc1MTMxMzcyNn0.U2JM1caZscU2826EM8yqoeVIkVfv-WckSOTrqXw-wDA

### PUT REQUEST ###
PUT http://localhost:3003/api/blogs/6867435d2e20e620297beee1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI0IiwiaWQiOiI2ODYyY2U2OTlkNGMzZTIxZTIxYzIzNDQiLCJpYXQiOjE3NTE2NTA4MzEsImV4cCI6MTc1MTY1NDQzMX0.NOznuJ-5JoakCgs_Vsg1vHCRGnK6Gnywq93UweYoXPk

{
	"author": "bacon guy",
	"url": "www.baconbacon.com"
}