### GET REQUEST ###
GET http://localhost:3003/api/blogs

### GOOD POST REQUEST ###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "New Book V3",
	"author": "Jane Doe",
	"url": "www.janedoebooks.com",
	"userId": "68609aeb414527252b56c95b"
}

### BAD POST REQUEST ###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "Some Book",
	"author": "John Doe"
}

### DELETE REQUEST ###
DELETE http://localhost:3003/api/blogs/686227a6cd4143e278b4e398